FPTJobMatch/Areas/Administrator/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FPTJobMatch.Data;
using FPTJobMatch.Models;
using FPTJobMatch.Repository.IRepository;
using Microsoft.AspNetCore.Identity;


namespace FPTJobMatch.Areas.Administrator.Controllers
{
    [Area("Administrator")]
	[Authorize(Roles = "Administrator")]

	public class UsersController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly UserManager<IdentityUser> _userManager;
		public UsersController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
		{
			_unitOfWork = unitOfWork;
			_userManager = userManager;
		}

		public IActionResult Index()
		{
			List<ApplicationUser> myList = _unitOfWork.AppUserRepository.GetAll().ToList();
			return View(myList);
		}
		public async Task<IActionResult> ToggleStatus(string id)
		{
			if (id == null)
			{
				return NotFound();
			}
			ApplicationUser? applicationUser = _unitOfWork.AppUserRepository.Get(c => c.Id == id);
			if (applicationUser == null)
			{
				return NotFound();
			}

			// Toggle the status
			applicationUser.Status = !applicationUser.Status;

			// Save changes
			_unitOfWork.Save();

			TempData["Success"] = applicationUser.Status ? "Account enabled successfully!" : "Account disabled successfully!";
			return RedirectToAction("Index");
		}


		public IActionResult Delete(string? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			ApplicationUser? applicationUser = _unitOfWork.AppUserRepository.Get(c => c.Id == id);
			if (applicationUser == null)
			{
				return NotFound();
			}

			return View(applicationUser);
		}

		[HttpPost, ActionName("Delete")]  //[HttpPost] or [HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirmed(string id)
		{
			ApplicationUser applicationUser = _unitOfWork.AppUserRepository.Get(c => c.Id == id);

			if (applicationUser == null)
			{
				return NotFound();
			}

			_unitOfWork.AppUserRepository.Delete(applicationUser);
			_unitOfWork.Save();
			TempData["Success"] = "Account deleted successfully!!";
			return RedirectToAction("index");
		}
	}
}

FPTJobMatch/Areas/Employer/Controllers/JobController.cs
using FPTJobMatch.Models;
using FPTJobMatch.Repository;
using FPTJobMatch.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;
using System.Security.Claims;

namespace FPTJobMatch.Areas.Employer.Controllers
{
    [Area("Employer")]
    [Authorize(Roles = "Employer")]
    public class JobController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        public JobController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
			var claimIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId != null)
            {
                var myList = _unitOfWork.JobRepository.GetAll("Category")
                    .Where(j => j.UserId == userId)  // Chỉ lấy các job thuộc về user hiện tại
                    .ToList();
                return View(myList);
            }
            return View(new List<Job>());
        }

		public IActionResult Create()
		{
			JobVM jobVM = new JobVM()
			{
				Categories = _unitOfWork.CategoryRepository.GetAll().Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = c.Name,
					Value = c.Id.ToString(),
				}),
				Job = new Job()
			};
			return View(jobVM);
		}
		[HttpPost]
		public IActionResult Create(JobVM jobVM)
		{
			if (ModelState.IsValid)
			{
				var claimIdentity = (ClaimsIdentity)User.Identity;
				var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

				if (userId != null)
				{
					jobVM.Job.UserId = userId;
					_unitOfWork.JobRepository.Add(jobVM.Job);
					_unitOfWork.JobRepository.Save();
					TempData["success"] = "Job created successfully";
					return RedirectToAction("Index");
				}
			}
			return View(jobVM);
		}

		public IActionResult Edit(int? id)
		{
			JobVM jobVM = new JobVM()
			{
				Categories = _unitOfWork.CategoryRepository.GetAll().Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = c.Name,
					Value = c.Id.ToString(),
				}),
				Job = _unitOfWork.JobRepository.Get(c => c.ID == id)
			};
			jobVM.Categories = _unitOfWork.CategoryRepository.GetAll().Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
			{
				Text = c.Name,
				Value = c.Id.ToString(),
			});
			return View(jobVM);
		}

		[HttpPost]
		public IActionResult Edit(JobVM jobVM)
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

			if (userId != null)
			{
				if (ModelState.IsValid)
				{
					jobVM.Job.UserId = userId;
					_unitOfWork.JobRepository.Update(jobVM.Job);
					_unitOfWork.JobRepository.Save();
					TempData["success"] = "Job edited successfully";
					return RedirectToAction("Index");
				}
			}
			return View(jobVM);
		}

		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Job? job = _unitOfWork.JobRepository.Get(c => c.ID == id, "Category");
			if (job == null)
			{
				return NotFound();
			}
			return View(job);
		}
		[HttpPost]
		public IActionResult Delete(Job job)
		{
			_unitOfWork.JobRepository.Delete(job);
			_unitOfWork.JobRepository.Save();
			TempData["success"] = "Job deleted successfully";
			return RedirectToAction("Index");
		}
		public IActionResult ViewJob(int? ID, string sortBy, string filterBy)
		{
			if (ID == null || ID == 0)
			{
				return NotFound();
			}

			// Lọc dữ liệu
			Expression<Func<ApplicationJob, bool>> filter = j => j.JobID == ID;
			var jobApps = _unitOfWork.ApplicationJobRepository.GetAllAppJob(filter);

			// Sắp xếp dữ liệu
			if (!string.IsNullOrEmpty(sortBy))
			{
				switch (sortBy)
				{
					case "email":
						jobApps = jobApps.OrderBy(j => j.Email);
						break;
					case "emailDesc":
						jobApps = jobApps.OrderByDescending(j => j.Email);
						break;
					case "dayApply":
						jobApps = jobApps.OrderBy(j => j.DayApply); // Sắp xếp theo ngày áp dụng giảm dần
						break;
					case "dayApplyDesc":
						jobApps = jobApps.OrderByDescending(j => j.DayApply); // Sắp xếp theo ngày áp dụng giảm dần
						break;
				}
			}

			// Search Email
			if (!string.IsNullOrEmpty(filterBy))
			{
				// Lọc theo Email
				jobApps = jobApps.Where(j => j.Email.Contains(filterBy));
			}

			return View(jobApps);
		}
		public async Task<IActionResult> ViewProfile(int? ID)
		{
			if (ID == null)
			{
				return NotFound();
			}

			var applicationJob = _unitOfWork.ApplicationJobRepository.Get(c => c.Id == ID);
			if (applicationJob == null)
			{
				return NotFound();
			}

			var jobSeeker = await _userManager.FindByEmailAsync(applicationJob.Email);
			if (jobSeeker == null)
			{
				return NotFound();
			}

			return View(jobSeeker);
		}

		public IActionResult Accept(int? ID)
		{
			if (ID == null)
			{
				return NotFound();
			}

			var jobApp = _unitOfWork.ApplicationJobRepository.Get(c => c.Id == ID);
			if (jobApp == null)
			{
				return NotFound();
			}

			jobApp.Status = true;
			_unitOfWork.ApplicationJobRepository.Update(jobApp);
			_unitOfWork.Save(); // Lưu thay đổi vào cơ sở dữ liệu

			return RedirectToAction("Index");
		}
		public IActionResult Decline(int? ID)
		{
			if (ID == null)
			{
				return NotFound();
			}

			var jobApp = _unitOfWork.ApplicationJobRepository.Get(c => c.Id == ID);
			if (jobApp == null)
			{
				return NotFound();
			}
			_unitOfWork.ApplicationJobRepository.Delete(jobApp);
			_unitOfWork.Save(); // Lưu thay đổi vào cơ sở dữ liệu

			return RedirectToAction("Index");
		}
	}
}

FPTJobMatch/Areas/JobSeeker/Controllers/ProfileController.cs
using FPTJobMatch.Models;
using FPTJobMatch.Repository.IRepository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FPTJobMatch.Areas.JobSeeker.Controllers
{
	[Area("JobSeeker")]
	public class ProfileController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly UserManager<IdentityUser> _userManager;
		private readonly IWebHostEnvironment _webHostEnvironment;
		public ProfileController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
			_userManager = userManager;
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}
		public async Task<IActionResult> Index()
		{
			var profile = await _userManager.GetUserAsync(User);
			return View(profile);
		}
		public IActionResult Edit(string? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			ApplicationUser? jobSeeker = _unitOfWork.AppUserRepository.Get(x => x.Id == id);
			if (jobSeeker == null)
			{
				return NotFound();
			}

			return View(jobSeeker);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(string id, ApplicationUser jobSeeker, IFormFile? avatarFile, IFormFile? cvFile)
		{
			if (id != jobSeeker.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					ApplicationUser user = (ApplicationUser)await _userManager.FindByIdAsync(id);
					user.Name = jobSeeker.Name;
					user.Address = jobSeeker.Address;
					user.Introduction = jobSeeker.Introduction;

					string wwwrootPath = _webHostEnvironment.WebRootPath;
					
					if (cvFile != null)
					{
						string cvFileName = Guid.NewGuid().ToString() + Path.GetExtension(cvFile.FileName);
						string cvPath = Path.Combine(wwwrootPath, @"img\cv");
						// Lưu CV mới nếu có
						if (cvFile != null)
						{
							// Delete Old CV
							if (!string.IsNullOrEmpty(jobSeeker.CV))
							{
								var oldCVPath = Path.Combine(wwwrootPath, jobSeeker.CV.TrimStart('\\'));
								if (System.IO.File.Exists(oldCVPath))
								{
									System.IO.File.Delete(oldCVPath);
								}
							}
							// Copy File to \img\cv
							using (var fileStream = new FileStream(Path.Combine(cvPath, cvFileName), FileMode.Create))
							{
								cvFile.CopyTo(fileStream);
							}
							// Update ImageUrl in DB
							user.CV = @"\img\cv\" + cvFileName;
						}
						else
						{
							// Copy File to \img\cv
							using (var fileStream = new FileStream(Path.Combine(cvPath, cvFileName), FileMode.Create))
							{
								cvFile.CopyTo(fileStream);
							}
							// Update ImageUrl in DB
							user.CV = @"\img\cv\" + cvFileName;
						}
					}

					// Cập nhật thông tin người dùng trong cơ sở dữ liệu
					_unitOfWork.AppUserRepository.Update(user);
					_unitOfWork.Save();
					TempData["success"] = "Profile edited successfully";
					return RedirectToAction("Index");
				}
				catch (Exception)
				{
					// Handle exception
					throw;
				}
			}
			return View(jobSeeker);
		}
	}
}

FPTJobMatch/Areas/JobSeeker/Controllers/ViewJobController.cs
using FPTJobMatch.Models;
using FPTJobMatch.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FPTJobMatch.Areas.JobSeeker.Controllers
{
    [Area("JobSeeker")]
    [Authorize(Roles = "JobSeeker")]
	public class ViewJobController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly UserManager<IdentityUser> _userManager;

		public ViewJobController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
		{
			_unitOfWork = unitOfWork;
			_userManager = userManager;
		}


		public IActionResult Index()
		{
			List<Job> myList = _unitOfWork.JobRepository.GetAll("Category").ToList();
			return View(myList);
		}

		public IActionResult Apply(int? ID)
		{
			if (ID == null)
			{
				return NotFound();
			}
			Job? job = _unitOfWork.JobRepository.Get(c => c.ID == ID);
			if (job == null)
			{
				return NotFound();
			}
			JobVM JobVm = new JobVM();
			JobVm.apply = new ApplicationJob();
			JobVm.apply.JobID = job.ID;
			JobVm.Job = job;

			return View(JobVm);
		}
		[HttpPost]
		public async Task<IActionResult> Apply(JobVM job)
		{
			if (ModelState.IsValid)
			{
				var currentUser = await _userManager.GetUserAsync(User);

				if (currentUser == null)
				{
					return RedirectToAction("Login", "Account");
				}

				job.apply.Email = currentUser.Email;

				DateTime currentDate = DateTime.Now;

				job.apply.DayApply = currentDate;

				_unitOfWork.ApplicationJobRepository.Add(job.apply);
				_unitOfWork.Save();

				TempData["success"] = "Job applied successfully";
				return RedirectToAction("Index");
			}
			return View(job);
		}
	}
}

FPTJobMatch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FPTJobMatch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FPTJobMatch.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="JobSeeker" asp-controller="Home" asp-action="Index">FPTJobMatch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                    
                        
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administrator" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administrator" asp-controller="Users" asp-action="Index">Account Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administrator" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                        }
                        @if (User.IsInRole("Employer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Employer" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Employer" asp-controller="Job" asp-action="Index">Job</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Employer" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                        }
                        @if (User.IsInRole("JobSeeker"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="JobSeeker" asp-controller="Home" asp-action="Index">[Home]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="JobSeeker" asp-controller="ViewJob" asp-action="Index">[Job]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="JobSeeker" asp-controller="Profile" asp-action="Index">[View Profile]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="JobSeeker" asp-controller="ApplicationStatus" asp-action="Index">[View Application Status]</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FPTJobMatch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FPTJobMatch/Views/Shared/_Notification.cshtml
﻿@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}